development:
  access_key_id: AKIAI2AVYGJ3CUGRYP6Q
  secret_access_key: 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
  bucket: akimono

test:
  access_key_id: AKIAI2AVYGJ3CUGRYP6Q
  secret_access_key: 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
  bucket: akimono

production:
  access_key_id: AKIAI2AVYGJ3CUGRYP6Q
  secret_access_key: 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
  bucket: akimono